; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = C:\Users\ForteZH\AppData\Local\Programs\Microsoft VS Code\ESP32CAM-ONVIF
default_envs = esp32cam

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/geeksville/Micro-RTSP.git
	bblanchon/ArduinoJson @ ^6.21.3
	madhephaestus/ESP32Servo @ ^1.1.1
	h2zero/NimBLE-Arduino @ ^1.4.2
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-Os
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections

[env:esp32cam]
board = esp32cam
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.partitions = huge_app.csv
